adjective = input("Enter a adjective: ")
type_of_bird = input("Enter a type of bird: ")
room_in_a_house = input("Enter a room in a house: ")
verb_past_tense = input("Enter a verb (past tense): ")
verb = input("Enter a verbb: ")
relative_name = input("Enter a relative`s_name: ")
noun = input("Enter a noun: ")
a_liquid = input("Enter a a_liquid : ")
verb_ending_in_ing = input("Enter a verb (ending in-ing) : ")
part_of_the_body_plural = input("Enter a part of the body(plural) : ")
plural_noun = input("Enter a plural_noun : ")

print("It was a " + adjective + ", cold November day.")
print("I woke up to the "+ adjective + " smell of "+ type_of_bird + " roasting in the " + room_in_a_house + " downstairs.")
print("I " + verb_past_tense + " down the stairs to see if I could help " + verb + " the dinner.")
print("Mt mom said, \"See if " + relative_name + " needs a fresh " + noun + " .\"")
print("So I carried a tray of glasses full of " + a_liquid + " into the " + verb_ending_in_ing + " room.")
print("When i got there, I couldn't believe my " + part_of_the_body_plural + " !")
print("There were " + plural_noun + verb_ending_in_ing + " on the " + noun + " !")